BaseURL = "http://communitypulse.io"
# BaseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Community Pulse"
theme = "castanet"
canonifyurls = false
buildFuture = false
buildDrafts = false
dataDir = "data"
# disqusShortname = "communitypulse"
archetypedir = "archetypes"
paginate = 9

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"
	sponsor = "/:filename"
	redirect = "/:filename"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
 [[Menu.Main]]
     name = "About"
     identifier = "about"
     url = "about"
 [[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"
 [[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"

[params]
site_theme = "grey"
site_layout = "grid"
enable_jumbo = "true"
favicon = "favicon.ico"
copyright_notice = "Copyright 2014-2019 [Community Pulse](https://www.communitypulse.io)"
itunes_subscribe = "https://itunes.apple.com/us/podcast/community-pulse/id1218368182?mt=2"
android_subscribe = "http://subscribeonandroid.com/communitypulse.libsyn.com/rss"
# google_play_subscribe = "https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
# stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
# pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
rss_subscribe = "http://communitypulse.libsyn.com/rss" #only set this if you don't want to use the built-in feed

Description = "Community Builders Mary Thengvall, Jason Hand, and PJ Hagerty interview experts in the field of Community Leadership and Management on a broad range of topics related to building community."
  [params.feed]
    feed_copyright = "Copyright 2013-2018 Arrested DevOps" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "There's always DevOps in the Banana Stand" #no markdown or HTML
    itunes_author = "Matty Stratton, Trevor Hess, Jessica Kerr, and Bridget Kromhout" #no markdown or HTML
    itunes_summary = "Arrested DevOps is the podcast that helps you achieve understanding, develop good practices, and operate your team and organization for maximum DevOps awesomeness." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    github = "mary-grace/community-pulse-source"
    # facebook = "Arresteddevops"
    # facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
    twitter = "community_pulse"
    twitter_domain = "http://communitypulse.io/" # This domain shows in twitter cards as "View on `twitter_domain`"
    # googleplus = "ArrestedDevOps"
    # pinterest = "arresteddevops"
    # instagram = "arresteddevops"
    youtube = "channel/UC3Mt417XSjzsIgekPWinKiw"

	[params.authors]
		[params.authors.Jason]
			name = "Jason Hand"
			thumbnail = "img/jason.png"
			bio = "DevOps Evangelist and Community Builder at VictorOps, organizer of DevOpsDays - Rockies, author of ChatOps for Dummies and O’Reilly’s ChatOps: Managing Operations from Group Chat. Jason has spent the last 3 years evangelizing for DevOps principles and concepts related to Post-mortems, ChatOps, Monitoring & Alerting, and the value of context within incident management. A frequent speaker at industry conferences and events around the country, Jason enjoys bring people together on a variety of technical and non-technical subjects."
			[params.authors.Jason.social]
				github = "jasonhand"
				twitter = "jasonhand"
	  [params.authors.Mary]
			name	= "Mary Thengvall"
			thumbnail = "img/mary.jpg"
			bio = "Mary Thengvall is a connector of people at heart, both personally and professionally. She loves digging into the strategy of how to build and foster communities, and has been working with various developer communities for over 7 years. She's now building out the community strategy for SparkPost, an API-driven email delivery service."
			[params.authors.Mary.social]
				github = "mary-grace"
				twitter = "mary_grace"
		[params.authors.PJ]
			name = "PJ Hagerty"
			thumbnail = "img/pj.jpg"
			bio = "Developer, writer, speaker, musician, and Technical Advocate at IBM Bluemix, PJ is known to travel the world speaking about programming and the way people think and interact. Traveling to conferences and meet ups around the world, PJ likes to spread the word on the importance of community and coding, stressing the importance of outreach and focusing on the human side of being a coder. He is also known for wearing hats."
			[params.authors.PJ.social]
				github = "aspleenic"
				twitter = "aspleenic"
